[project]
name = "semantic-kernel-workshop"
version = "0.1.0"
description = "A workshop for Semantic Kernel"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "mermaid-py>=0.7.1",
    "python-dotenv==1.0.1",
    "semantic-kernel[azure]==1.27.2",
]
